### ISSUE TITLE
Fix wrong default port

### ISSUE THREAD

**Issue by JeremyPansier** [my-cloud/ruthenium#63]
The default port is 8106 instead of 8080

* [x] change the default port from 8106 to 8080

**Comment by JeremyPansier** [comment]
In the "ruthenium\src\ui\main.go" file, the `port` program argument default value is `blockchain.DefaultPort` (8106). It should be replaced by another constant ahving the value 8080. This constant might be defined in the `ruthenium\src\ui\server\controller.go`  file.

**Comment by GrantOkawa** [comment]
I can take a look into this issue and try and solve it for you.

**Comment by GrantOkawa** [comment]
Created a pull request to be reviewed for this issue let me know how it looks.

**Comment by JeremyPansier** [comment]
> Created a pull request to be reviewed for this issue let me know how it looks.

Hello @GrantOkawa, many thanks for your contributinon to this project. I suggested you some changes in the [PR](https://github.com/my-cloud/ruthenium/pull/64#discussion_r982087641). Do you have any question or concern?
